server:
  port: 9002
  servlet:
    context-path: /auth-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #显示服务器IP
spring:
  application:
    name: auth-user
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置数据库方
security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8999/auth-user/oauth/authorize
      access-token-uri: http://localhost:8999/auth-user/oauth/token
    #    resource:
    #      id: user-client
    #      user-info-uri: user-info
    #    authorization:
    #      check-token-access: http://localhost:6001/oauth/check_token
    resource:
      jwt:
        key-uri: http://localhost:8999/auth-user/oauth/token_key
        key-value: dev
management:
  endpoint:
    health:
      enabled: true

logging:
  level:
    org.springframework.security: info