spring:
  datasource:
   -  jdbc-url: jdbc:mysql://127.0.0.1:3306/multi-data-source-01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
   -  jdbc-url: jdbc:mysql://127.0.0.1:3306/multi-data-source-02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
