server:
  port: 8083
wf:
  oauth:
    clientid: wf_oauth
    secret: wf_secret
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true #显示服务器IP
spring:
  application:
    name: auth-server