server:
  servlet:
    context-path: /gateway
  port: 8999
spring:
  application:
    name: client-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，# 这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了,比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上
      routes:
        - id: backend
          uri: lb://backend
          order: -1
          predicates:
            - Path=/backend/**
          filters:
            - StripPrefix=0 # 去掉/backend前缀
        - id: auth-user
          uri: lb://auth-user
          order: -1
          predicates:
            - Path=/auth-user/**
          filters:
            - StripPrefix=0 # 去掉/auth-user前缀
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #显示服务器IP