mybatis:
  typeAliasesPackage: com.example.backend.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.example.backend.mapper/*.xml
server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: backend
  kafka:
    producer:
      bootstrap-servers: 118.25.11.28:29092 #生产者
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 118.25.11.28:29092
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always