mybatis:
  typeAliasesPackage: com.example.backend.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.example.backend.mapper/*.xml
server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: backend
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always