mybatis:
  typeAliasesPackage: com.gg.backend.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.gg.backend.mapper/*.xml
server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: backend
  kafka:
    producer:
      bootstrap-servers: 118.25.11.28:29092 #生产者
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 118.25.11.28:29092
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  quartz:
    job-store-type: jdbc
    # 初始化表
    jdbc:
      initialize-schema: never
    # quartz 属性配置
    properties:
      org:
        quartz:
          scheduler:
            # 如果使用集群，实例名需相同
            instanceName: QuartzScheduler
            # 如果使用集群，id需相同
            instanceId: CLUSTERED
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #显示服务器IP
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:9002/oauth/authorize
      access-token-uri: http://localhost:9002/oauth/token
    #    resource:
    #      id: user-client
    #      user-info-uri: user-info
    #    authorization:
    #      check-token-access: http://localhost:6001/oauth/check_token
    resource:
      jwt:
        key-uri: http://localhost:9002/oauth/token_key
        key-value: dev